# Generated by Django 3.2.6 on 2021-10-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='Content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='thumb',
            new_name='Thumb',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Title',
        ),
        migrations.AddField(
            model_name='post',
            name='Sub_Title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='blog_post', to='Blog.Register'),
        ),
    ]
