# Generated by Django 3.2.6 on 2021-10-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_auto_20211016_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Sub_Title',
        ),
    ]
