# Generated by Django 3.2.6 on 2021-11-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_auto_20211115_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='SubHeading',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
