# Generated by Django 3.2.6 on 2021-11-18 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0011_auto_20211115_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='account',
            name='LastName',
        ),
        migrations.AddField(
            model_name='account',
            name='firstName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='lastName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='Email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
