# Generated by Django 3.2.7 on 2022-02-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_auto_20220225_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='SubHeading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
